config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new' #rota pradrão
  
  #Rotas Paciente
  get :search, controller: :pacients
  #root to: "pacients#new"
  get :professionAtualiza, controller: :pacients
  get :serviceAccessAtualiza, controller: :pacients
  get :ubAtualiza, controller: :pacients


  get 'sessions/new'
  
  #Gerando rotas para PDF
  get "/articles", to: "articles#index", as: :articles
  

  resources :users
  
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'

  #resources :prms
  resources :service_accesses
  resources :professions
  resources :ubs
  resources :pacients
  
  ###Rotas Atendimento
  resources :attendances
  resources :prm_causes
  resources :pharmacotherapies
  resources :prms
  resources :diseases
  resources :treatments
  resources :sfcs
  resources :care_plans
  resources :home 
  resources :type_sexes 
  
end

app/models/treatment.rb
class Treatment < ActiveRecord::Base
  belongs_to :disease
  belongs_to :attendance
  
  
    
end

app/controllers/treatments_controller.rb
class TreatmentsController < ApplicationController
  before_action :authorize
  
  before_action :set_treatment, only: [:show, :edit, :update, :destroy]

  # GET /treatments
  # GET /treatments.json
  def index
    @treatments = Treatment.all
  end

  # GET /treatments/1
  # GET /treatments/1.json
  def show
  end

  # GET /treatments/new
  def new
    @treatment = Treatment.new
  end

  # GET /treatments/1/edit
  def edit
  end

  # POST /treatments
  # POST /treatments.json
  def create
    @treatment = Treatment.new(treatment_params)

    respond_to do |format|
      if @treatment.save
        format.html { redirect_to @treatment, notice: 'Tratamento criado com sucesso.' }
        format.json { render :show, status: :created, location: @treatment }
      else
        format.html { render :new }
        format.json { render json: @treatment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /treatments/1
  # PATCH/PUT /treatments/1.json
  def update
    respond_to do |format|
      if @treatment.update(treatment_params)
        format.html { redirect_to @treatment, notice: 'Tratamento alterado com sucesso.' }
        format.json { render :show, status: :ok, location: @treatment }
      else
        format.html { render :edit }
        format.json { render json: @treatment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /treatments/1
  # DELETE /treatments/1.json
  def destroy
    @treatment.destroy
    respond_to do |format|
      format.html { redirect_to treatments_url, notice: 'Tratamento deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_treatment
      @treatment = Treatment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def treatment_params
      params.require(:treatment).permit(:disease_id, :attendance_id)
    end
end

app/helpers/treatments_helper.rb
module TreatmentsHelper
end

app/views/treatments/_form.html.erb
<%= form_for(@treatment) do |f| %>
  <% if @treatment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@treatment.errors.count, "error") %> prohibited this treatment from being saved:</h2>

      <ul>
      <% @treatment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :disease_id %><br>
    <%= f.text_field :disease_id %>
  </div>
  <div class="field">
    <%= f.label :attendance_id %><br>
    <%= f.text_field :attendance_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/treatments/edit.html.erb
<h1>Editing Treatment</h1>

<%= render 'form' %>

<%= link_to 'Show', @treatment %> |
<%= link_to 'Back', treatments_path %>

app/views/treatments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Treatments</h1>

<table>
  <thead>
    <tr>
      <th>Disease</th>
      <th>Attendance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @treatments.each do |treatment| %>
      <tr>
        <td><%= treatment.disease %></td>
        <td><%= treatment.attendance %></td>
        <td><%= link_to 'Show', treatment %></td>
        <td><%= link_to 'Edit', edit_treatment_path(treatment) %></td>
        <td><%= link_to 'Destroy', treatment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Treatment', new_treatment_path %>

app/views/treatments/new.html.erb
<h1>New Treatment</h1>

<%= render 'form' %>

<%= link_to 'Back', treatments_path %>

app/views/treatments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Disease:</strong>
  <%= @treatment.disease %>
</p>

<p>
  <strong>Attendance:</strong>
  <%= @treatment.attendance %>
</p>

<%= link_to 'Edit', edit_treatment_path(@treatment) %> |
<%= link_to 'Back', treatments_path %>