config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new' #rota pradrão
  
  #Rotas Paciente
  get :search, controller: :pacients
  #root to: "pacients#new"
  get :professionAtualiza, controller: :pacients
  get :serviceAccessAtualiza, controller: :pacients
  get :ubAtualiza, controller: :pacients


  get 'sessions/new'
  
  #Gerando rotas para PDF
  get "/articles", to: "articles#index", as: :articles
  

  resources :users
  
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'

  #resources :prms
  resources :service_accesses
  resources :professions
  resources :ubs
  resources :pacients
  
  ###Rotas Atendimento
  resources :attendances
  resources :prm_causes
  resources :pharmacotherapies
  resources :prms
  resources :diseases
  resources :treatments
  resources :sfcs
  resources :care_plans
  resources :home 
  resources :type_sexes 
  
end

app/models/care_plan.rb
class CarePlan < ActiveRecord::Base
  
  belongs_to :pharmacotherapy
  belongs_to :prm
  belongs_to :sfc
  belongs_to :prmCause
  belongs_to :attendance

  
  has_many :pharmacotherapy
 
  
  
  
  #validates_presence_of :therapeutic_goal, message: 'não pode deixar em branco'
  #validates_presence_of :conduct, message: 'não pode deixar em branco'
  ##validates_presence_of :pharmacotherapy, message: 'não pode deixar em branco'
  ##validates_presence_of :prm, message: 'não pode deixar em branco'
  ##validates_presence_of :prmCause, message: 'não pode deixar em branco'
  
  
  
  
  #validates_presence_of :sfc, message: 'não pode deixar em branco'
  
end

app/controllers/care_plans_controller.rb
class CarePlansController < ApplicationController
  before_action :authorize
  
  before_action :set_care_plan, only: [:show, :edit, :update, :destroy]

  # GET /care_plans
  # GET /care_plans.json
  def index
    @care_plans = CarePlan.all
  end

  # GET /care_plans/1
  # GET /care_plans/1.json
  def show
  end

  # GET /care_plans/new
  def new
    @care_plan = CarePlan.new
  end

  # GET /care_plans/1/edit
  def edit
  end

  # POST /care_plans
  # POST /care_plans.json
  def create
    @care_plan = CarePlan.new(care_plan_params)

    respond_to do |format|
      if @care_plan.save
        format.html { redirect_to @care_plan, notice: 'Plano de cuidado criado com sucesso.' }
        format.json { render :show, status: :created, location: @care_plan }
      else
        format.html { render :new }
        format.json { render json: @care_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /care_plans/1
  # PATCH/PUT /care_plans/1.json
  def update
    respond_to do |format|
      if @care_plan.update(care_plan_params)
        format.html { redirect_to @care_plan, notice: 'Plano de cuidade alterado com sucesso.' }
        format.json { render :show, status: :ok, location: @care_plan }
      else
        format.html { render :edit }
        format.json { render json: @care_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /care_plans/1
  # DELETE /care_plans/1.json
  def destroy
    @care_plan.destroy
    respond_to do |format|
      format.html { redirect_to care_plans_url, notice: 'Plano de cuidado deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_care_plan
      @care_plan = CarePlan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def care_plan_params
      params.require(:care_plan).permit(:therapeutic_goal, :conduct, :results_date, :anothers_conduct, :pharmacotherapy_id, :prm_id, :sfc_id, :prmCause_id, :pacient_id)
    end
end

app/helpers/care_plans_helper.rb
module CarePlansHelper
end

app/views/care_plans/_form.html.erb
<%= form_for(@care_plan) do |f| %>
  <% if @care_plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@care_plan.errors.count, "error") %> Não foi possivel salvar esse registro:</h2>

      <ul>
      <% @care_plan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">
      <form id="demo-form" data-parsley-validate>
        <div class="x_panel">
          <div class="x_title">
            <h2>Plano de Cuidados</h2>
            
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          
          <div class="x_content">
            <div class="row">
              
              <div class="col-md-4 col-sm-12 col-xs-12 form-group">
                <label class="heard">Paciente:</label>
                  <%= f.select :attendance,
                      Attendance.all.map { |u| ["#{u.pacient.name} - #{u.attendance_date}", u.id] },
                      { include_blank: "Buscar Atendimento" },
                      { class: 'select2_single form-control' }
                  %>
              </div>
              
              
              <div class="col-md-8 col-sm-12 col-xs-12 form-group">
                <label class="heard">Objetivo terapêutico:</label>
                  <%= f.text_field :therapeutic_goal, :class => "form-control" %>
              </div>
              
              <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                <label class="heard">Conduta:</label>
                  <%= f.text_field :conduct, :class => "form-control" %>
              </div>
                </div>
              <label class="col-md-2 control-label">Data dos resultados:</label>
               
                 
               
               
                <div class="col-md-4">
                  
                  
                  <label class="col-md-6 control-label">Data dos Resultados:</label>
                  <div id="calendario" class="input-group date" data-provide="datepicker">
                    <%= f.text_field :results_date, {class: "form-control col-md-7 col-xs-12"}%>
                    <div class="input-group-addon">
                        <span class="glyphicon glyphicon-th"></span>
                    </div>
                  </div>
                  
                </div>
              <label class="col-md-2 control-label">Outra conduta:</label>
                <div class="col-md-4">
                  <%= f.text_field :anothers_conduct, :class => "form-control" %>
                </div>
                
                <label class="col-md-2 control-label">Outra conduta:</label>
                <div class="col-md-4">
                  <%= f.text_field :anothers_conduct, :class => "form-control" %>
                </div>
                
                <label class="col-md-2 control-label">Outra conduta:</label>
                <div class="col-md-4">
                  <%= f.text_field :anothers_conduct, :class => "form-control" %>
                </div>
                
                <label class="col-md-2 control-label">Outra conduta:</label>
                <div class="col-md-4">
                  <%= f.text_field :anothers_conduct, :class => "form-control" %>
                </div>
              
              <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                <label for="heard">Data do Resultado:</label>
                  <div id="calendario" class="input-group date" data-provide="datepicker">
                    <%= f.text_field :results_date, {class: "form-control col-md-7 col-xs-12"}%>
                    <div class="input-group-addon">
                        <span class="glyphicon glyphicon-th"></span>
                    </div>
                  </div>
              </div>
              
              <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                <label class="heard">Outra conduta:</label>
                  <%= f.text_field :anothers_conduct, :class => "form-control" %>
              </div>
                
              <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                <label class="heard">SFC:</label>
                <div class="input-group col-md-12 col-sm-12 col-xs-12 form-group">
                  <%= f.select :sfc_id,
                    Sfc.all.map { |u| [u.description, u.id] },
                    { include_blank: "Buscar SFC" },
                    { class: 'chosen-select' }
                  %>
                </div>
              </div>
            </div>
          </div>
        </div> 
    </form>
    
  <div class="actions">
    <%= f.submit 'Salvar', :class => 'btn btn-success' %>
  </div>
</div>    

<% end %>

app/views/care_plans/edit.html.erb
<h1>Editando Plano de Cuidados</h1>

<%= render 'form' %>

<%= link_to 'Visualizar', @care_plan, :class => 'btn btn-primary' %> | <%= link_to 'Voltar', care_plans_path, :class => 'btn btn-primary' %>

app/views/care_plans/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Novo Plano de Cuidado', new_care_plan_path, :class => 'btn btn-primary' %>

<h1>Lista Plano de Cuidado</h1>

<div class="container-fluid">
  <div class="row">
      <div class="col-sm-12">
       <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th>Objetivo terapêutico</th>
              <th>Conduta</th>
              <th>Data dos resultados</th>
              <th>Outra conduta</th>
              <th>SFC</th>
              <th colspan="3">Ações</th>
            </tr>
          </thead>
        
          <tbody>
            <% @care_plans.each do |care_plan| %>
              <tr>
                <td><%= care_plan.therapeutic_goal %></td>
                <td><%= care_plan.conduct %></td>
                <td><%= care_plan.results_date %></td>
                <td><%= care_plan.anothers_conduct %></td>
                <td><%= care_plan.sfc.description %></td>
                <td><%= link_to 'Visualizar', care_plan, :class => 'btn btn-primary' %></td>
                <td><%= link_to 'Editar', edit_care_plan_path(care_plan), :class => 'btn btn-primary' %></td>
                <td><%= link_to 'Excluir', care_plan, :class => 'btn btn-primary', method: :delete, data: { confirm: 'Confirma a exclusão?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/care_plans/new.html.erb
<%= link_to 'Voltar', care_plans_path, :class => 'btn btn-primary' %>

<h1>Novo Plano de Cuidados</h1>

<%= render 'form' %>

app/views/care_plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Paciente:</strong>
  <!--%= @care_plan.attendance.pacient.name %-->
</p>
<p>
  <strong>Data do Atendimento:</strong>
  <!--%= @care_plan.attendance.attendance_date %-->
</p>

<p>
  <strong>Objetivo terapêutico:</strong>
  <%= @care_plan.therapeutic_goal %>
</p>

<p>
  <strong>Conduta:</strong>
  <%= @care_plan.conduct %>
</p>

<p>
  <strong>Data dos resultados:</strong>
  <%= @care_plan.results_date %>
</p>

<p>
  <strong>Outra conduta:</strong>
  <%= @care_plan.anothers_conduct %>
</p>

<p>
  <strong>Outra conduta:</strong>
  <%= @care_plan.anothers_conduct %>
</p>

<p>
  <strong>Outra conduta:</strong>
  <%= @care_plan.anothers_conduct %>
</p>

<p>
  <strong>Outra conduta:</strong>
  <%= @care_plan.anothers_conduct %>
</p>



<p>
  <strong>SFC:</strong>
  <%= @care_plan.sfc.description %>
</p>



<%= link_to 'Editar', edit_care_plan_path(@care_plan), :class => 'btn btn-primary' %> | <%= link_to 'Voltar', care_plans_path, :class => 'btn btn-primary' %>