config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new' #rota pradrão
  
  #Rotas Paciente
  get :search, controller: :pacients
  #root to: "pacients#new"
  get :professionAtualiza, controller: :pacients
  get :serviceAccessAtualiza, controller: :pacients
  get :ubAtualiza, controller: :pacients


  get 'sessions/new'
  
  #Gerando rotas para PDF
  get "/articles", to: "articles#index", as: :articles
  

  resources :users
  
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'

  #resources :prms
  resources :service_accesses
  resources :professions
  resources :ubs
  resources :pacients
  
  ###Rotas Atendimento
  resources :attendances
  resources :prm_causes
  resources :pharmacotherapies
  resources :prms
  resources :diseases
  resources :treatments
  resources :sfcs
  resources :care_plans
  resources :home 
  resources :type_sexes 
  
end

app/models/pacient.rb
class Pacient < ActiveRecord::Base
    
    #Relacionamentos
  has_many :pacients
  has_many :prms
  has_many :prm_causes
  has_many :diseases
  has_many :pharmacotherapies
  has_many :sfcs
  has_many :care_plans
  has_many :attendances
  
    
  belongs_to :pacient
  belongs_to :prm
  belongs_to :prm_cause
  belongs_to :disease
  belongs_to :pharmacotherapy
  belongs_to :sfc
  belongs_to :care_plan
  belongs_to :attendance
  
    #Pesquisa
    scope :pesquisa, ->(query) {where("cpf like ?", "%#{query}%")}
    
    #Relacionamentos
    has_many :profession, as: :description  #tem que pegar o id e não a description da profissão
    has_many :ub, as: :description   #tem que pegar o id e não a description
    has_many :service_access, as: :description   #tem que pegar o id e não a description
    
    
    has_many :professions
    has_many :ubs
    has_many :service_access
    
    belongs_to :profession
    belongs_to :service_access
    belongs_to :ub
    
    
    validates :name, presence: {message: 'não pode ser deixado em branco'},
                     length: {in: 3..100, message: 'deve conter de 3 a 100 caracteres'}
    
    validates :phone, presence: {message: 'não pode ser deixado em branco'},
                      #numericality: {:greater_than_or_equal_to => 0, message: 'deve conter somente números positivos'},
                      length: {in: 10..14, message: 'deve conter de 10 à 11 números'}
                      #numericality: {message: 'deve conter somente número'},
                      #length: {minimum: 10, message: 'deve conter no mínimo 10 números'}
    
    #validates :years_study, length: {in: 0..50, message: 'deve conter de 10 à 11 números'}
                            
    validates_length_of :years_study, minimum: 0, message: 'o número deve ser maior ou igual a 0.'
    validates_length_of :years_study, maximum: 50, message: 'pode conter até 50 números'
    
    validates :genre, numericality: {:greater_than => 0, message: 'deve ser selecionado'}
    
    validates :marital_status, numericality: {:greater_than => 0, message: 'deve ser selecionado'}
    
    validates :cpf, presence: {message: 'não pode ser deixado em branco'},
                    #numericality: {message: 'deve conter somente número!'},
                    length: {is: 14, message: 'deve conter 14 números!'}    
                                
    validates_uniqueness_of :cpf, message: 'Este CPF já está cadastrado!'   

    
    
end

app/controllers/pacients_controller.rb
class PacientsController < ApplicationController
  before_action :authorize
  attr_accessor :profession
  attr_accessor :ub
  attr_accessor :service_access
  before_action :set_pacient, only: [:show, :edit, :update, :destroy]

  # GET /pacients
  # GET /pacients.json
  def index
    if params[:pesquisa]
      @pacients = Pacient.pesquisa(params[:pesquisa])
    else
      @pacients = Pacient.all
    end
  end

  # GET /pacients/1
  # GET /pacients/1.json
  def show
    @attendances = Attendance.where(pacient_id: @pacient.id).order(attendance_date: :desc)
    # @professionAtualiza = Profession.all.map { |u| [u.description, u.id] }
    # @ubAtualiza = Ub.all.map { |u| [u.description, u.id] }
    # @serviceAccessAtualiza = ServiceAccess.all.map { |u| [u.description, u.id] }
  end
  
  # GET /pacients/new
  def new
    @pacient = Pacient.new
    @profession = Profession.new
    @ub = Ub.new
    @service_access = ServiceAccess.new
    
    # @professionAtualiza = Profession.all.map { |u| [u.description, u.id] }
    # @ubAtualiza = Ub.all.map { |u| [u.description, u.id] }
    # @serviceAccessAtualiza = ServiceAccess.all.map { |u| [u.description, u.id] }
  end

  # GET /pacients/1/edit
  def edit
    # @professionAtualiza = Profession.all.map { |u| [u.description, u.id] }
    # @ubAtualiza = Ub.all.map { |u| [u.description, u.id] }
    # @serviceAccessAtualiza = ServiceAccess.all.map { |u| [u.description, u.id] }
  end
  
  # def updateProfessionAtualiza
  #   @professionAtualiza = Profession.all.map { |u| [u.description, u.id] }
  # end
  
  # def updateUbAtualiza
  #   @ubAtualiza = Ub.all.map { |u| [u.description, u.id] }
  # end
  
  # def updateServiceAccessAtualiza
  #   @serviceAccessAtualiza = ServiceAccess.all.map { |u| [u.description, u.id] }
  # end

  # POST /pacients
  # POST /pacients.json
  def create
    @pacient = Pacient.new(pacient_params)
    @profession = Profession.new
    @ub = Ub.new
    @service_access = ServiceAccess.new

    respond_to do |format|
      if @pacient.save
        format.html { redirect_to @pacient, notice: 'Paciente criado com sucesso.' }
        format.json { render :show, status: :created, location: @pacient }
      else
        format.html { render :new }
        format.json { render json: @pacient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pacients/1
  # PATCH/PUT /pacients/1.json
  def update
    respond_to do |format|
      if @pacient.update(pacient_params)
        format.html { redirect_to @pacient, notice: 'Paciente alterado com sucesso.' }
        format.json { render :show, status: :ok, location: @pacient }
      else
        format.html { render :edit }
        format.json { render json: @pacient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pacients/1
  # DELETE /pacients/1.json
  def destroy
    @pacient.destroy
    respond_to do |format|
      format.html { redirect_to pacients_url, notice: 'Paciente excluido com sucesso.' }
      format.json { head :no_content }
    end
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pacient
      @pacient = Pacient.find(params[:id])
    end

    def calculate_imc
        @weight = params[:weight].to_f
        @height = params[:height].to_f
        @IMC = (@weight/(@height*@height))
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def pacient_params
      params.require(:pacient).permit(:name, :place_attendence, :birth_date, :years_study, :genre, 
                                      :marital_status, :phone, :address, :services_professional, 
                                      :reason_meeting, :cpf, :profession_id, :service_access_id, :ub_id, 
                                      :physical_activity, :alcoholic_beverages, :cigarette, :daily_routine,
                                      :alternative_therapy, :alerts, :subjective_medications, :weight, 
                                      :height, :IMC, :wakeupat, :breakfast, :snack, :lunch, :latesnack,
                                      :dinner, :sleepat , :obs, :obsdrink, :obsphysical)
    end
end

app/helpers/pacients_helper.rb
module PacientsHelper

def phone_format number
    if !number.nil?
        raw "<span class='phone-number'>#{number}</span>"
    end
end    
    
end

app/views/pacients/_atualiza.html.erb
<nav id="menu">
    <button id="atualiza-prof">ProfissãoHome</button>
</nav>

<div id="all">
    <div class="f" id="atualiza=prof">ProfissãoConteudo</div>
</div>


<nav id="menuServiceAccess">
    <button id="atualiza-service">ServiceAccessHome</button>
</nav>

<div id="allServiceAccess">
    <div class="f" id="atualiza=service">ServiceAccessConteudo</div>
</div>


<nav id="menuUb">
    <button id="atualiza-ub">UbHome</button>
</nav>

<div id="allUb">
    <div class="f" id="atualiza=ub">UbConteudo</div>
</div>

app/views/pacients/edit.html.erb
<h1>Editando paciente</h1>

<%= render 'form' %>

<%= link_to 'Visualizar', @pacient, :class => 'btn btn-primary' %> |
<%= link_to 'Voltar', pacients_path, :class => 'btn btn-primary' %>

app/views/pacients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Pacientes</h1>
<%= link_to '<i class="glyphicon glyphicon-plus"></i>Novo Paciente'.html_safe, new_pacient_path, :class =>'btn btn-primary' %>

<%= form_tag(pacients_path, :method => :get) do %>
  <%= text_field_tag 'pesquisa', nil, placeholder: 'Buscar por CPF' %>
  <%= submit_tag "Pesquisar" , :class => 'btn btn-primary'%>
<% end %>
<div class="container-fluid">
  <div class="row">
      <div class="col-lg-12">
       <div class="table-responsive">
        <table class="table">
          <thead>
           <tr>
                <th>Nome</th>
                <th style="width: 12%">CPF</th>
                <th>Lugar de Atendimento</th>
                <th style="width: 12%">Telefone</th>
                <th>Endereço</th>
                <th>Profissional Serviço</th>
                <th>Motivo Consulta</th>
                <th style="width: 20%">Ações</th>
              </tr>
            </thead>
            <tbody>
              <% @pacients.each do |pacient| %>
                <tr>
                  <td><%= link_to pacient.name.html_safe, pacient %></td>
                  <td><%= pacient.cpf %></td>
                  <td><%= pacient.place_attendence %></td>
                  <td><%= pacient.phone %></td>
                  <td><%= pacient.address %></td>
                  <td><%= pacient.services_professional %></td>
                  <td><%= pacient.reason_meeting %></td>
                  <td>
                    <div class="btn-group">
                      <a href="/attendances/new?idPaciente=<%=pacient.id%>" class="btn btn-primary">Novo Atendimento</a>
                      <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_pacient_path(pacient), :class => 'btn btn-warning', "data-original-title" => "Editar", "data-placement" => "top", "data-toggle" => "tooltip" %>
                      <!--<%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, pacient, :class => 'btn btn-danger', method: :delete, data: { confirm: 'Confirma a exclusão?' }, "data-original-title" => "Delete", "data-placement" => "top", "data-toggle" => "tooltip" %>-->
                    </div>  
                  </td>  
                </tr>
              <% end %>
            </tbody>
          </table>
      </div>
    </div>
  </div>
</div>

app/views/pacients/new.html.erb
<h1>Novo paciente</h1>

<!--div-->
  <!--%= link_to 'Nova Profissão', new_profession_path, :remote => true, :class => 'btn btn-primary' %-->
<!--/div-->

<%= render 'form' %>

<div id="new-profession" style="display:none;">
    <%= render 'professions/new'%>    
</div>

<div id="new-ub" style="display:none;">
    <%= render 'ubs/new'%>    
</div>

<div id="new-service_access" style="display:none;">
    <%= render 'service_accesses/new'%>    
</div>

app/views/pacients/show.html.erb
<div class="x_panel">
          <div class="x_title">
            <h2>Dados do Paciente</h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          
         <div class="row">
                        <div class="col-xs-8 table">
                          <table class="table table-bordered">
          
            <p id="notice"><%= notice %></p>

            <tr>
             <td> <strong>Nome:</strong> </td>
              <td> <%= @pacient.name %> </td>
            </tr>

            <tr>
              <td><strong>Lugar de atendimento:</strong></td>
             <td> <%= @pacient.place_attendence %> </td>
            </tr>

            <tr>
              <td><strong>Data de nascimento:</strong></td>
              <td><%= @pacient.birth_date %> </td>
            </tr>

            <tr>
              <td><strong>Anos de estudo:</strong></td>
              <td><%= @pacient.years_study %></td>
            </tr>

            <tr>
              <td><strong>Sexo:</strong></td>
              <td><%= @pacient.genre %> </td>
            </tr>

            <tr>
              <td><strong>Estado civil:</strong></td>
              <td><%= @pacient.marital_status %></td>
            </tr>

            <tr>
              <td><strong>Telefone:</strong></td>
              <td><%= @pacient.phone %></td>
            </tr>

            <tr>
              <td><strong>Endereço:</strong></td>
              <td><%= @pacient.address %></td>
            </tr>
            
            <tr>
              <td><strong>Profissional serviço:</strong></td>
              <td><%= @pacient.services_professional %> </td>
            </tr>

            <tr>
              <td><strong>Motivo do encontro:</strong></td>
              <td><%= @pacient.reason_meeting %> </td>
            </tr>

            <tr>
              <td><strong>CPF:</strong></td>
              <td><%= @pacient.cpf %> </td>
            </tr>
            
            <p>
              <strong>Profissão:</strong>
              <%= @pacient.profession.description %>
            </p>

            <p>
              <strong>UBS:</strong>
              <%= @pacient.ub.description %>
            </p>

            <p>
              <strong>Acesso ao Serviço:</strong>
              <%= @pacient.service_access.description %>
            </p>
            
            <p>
              <strong>Atividade Fisica:</strong>
              <%= @pacient.physical_activity %>
            </p>
            
            <p>
              <strong>Cigarro:</strong>
              <%= @pacient.cigarette %>
            </p>

            <p>
              <strong>Bebidas Alcoólicas:</strong>
              <%= @pacient.alcoholic_beverages %>
            </p>

            <p>
              <strong>Rotina Diária:</strong>
              <%= @pacient.daily_routine %>
            </p>
            
            <p>
              <strong>Alertas:</strong>
              <%= @pacient.alerts %>
            </p>

            <p>
              <strong>Terapia Alternativa:</strong>
              <%= @pacient.alternative_therapy %>
            </p>
            
            <p>
              <strong>Experiência subjetiva com o uso de medicamento:</strong>
              <%= @pacient.subjective_medications %>
            </p>
            <p>
              <strong>Peso:</strong>
              <%= @pacient.weight %>
            </p>
            <p>
              <strong>Altura:</strong>
              <%= @pacient.height %>
            </p>
            <p>
              <strong>IMC:</strong>
              <%= @pacient.IMC %>
            </p>
            <%= link_to 'Editar', edit_pacient_path(@pacient), :class => 'btn btn-warning' %> | <%= link_to 'Voltar', pacients_path, :class => 'btn btn-primary' %>
          </div>
          </table>
          <%= link_to 'Editar', edit_pacient_path(@pacient), :class => 'btn btn-warning' %> | <%= link_to 'Voltar', pacients_path, :class => 'btn btn-primary' %>
          

           <div class="x_title">
            <h2>Atendimento(s) do Paciente</h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          
         <div class="x_content">  
         
           <div class="container-fluid">
             <td><a href="/attendances/new?idPaciente=<%=@pacient.id%>" class="btn btn-primary">Novo Atendimento</a></td>
              <div class="row">
                <div class="col-sm-12">
                  <div class="table-responsive">
                    <table class="table">
                      <thead>
                        <tr>
                          <th>Data do atendimento</th>
                          <th>Quadro geral</th>
                          <th colspan="2"></th>
                        </tr>
                      </thead>
          
                    <tbody>
                      <% @attendances.each do |attendance| %>
                        <tr>
                          <td><%= attendance.attendance_date %></td>
                          <td><%= attendance.general_screen %></td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
         
         
        </div>
</div>