config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new' #rota pradrão
  
  #Rotas Paciente
  get :search, controller: :pacients
  #root to: "pacients#new"
  get :professionAtualiza, controller: :pacients
  get :serviceAccessAtualiza, controller: :pacients
  get :ubAtualiza, controller: :pacients


  get 'sessions/new'
  
  #Gerando rotas para PDF
  get "/articles", to: "articles#index", as: :articles
  

  resources :users
  
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'

  #resources :prms
  resources :service_accesses
  resources :professions
  resources :ubs
  resources :pacients
  
  ###Rotas Atendimento
  resources :attendances
  resources :prm_causes
  resources :pharmacotherapies
  resources :prms
  resources :diseases
  resources :treatments
  resources :sfcs
  resources :care_plans
  resources :home 
  resources :type_sexes 
  
end

app/models/prm.rb
class Prm < ActiveRecord::Base
    scope :pesquisa, ->(query) {where("description ?", "%#{query}%")}
    scope :pesquisa, ->(query) {where("description like ?", "%#{query}%")}
    
    
    belongs_to :attendance
    belongs_to :care_plan
    belongs_to :pharmacotherapy
    
    
    #Relacionamentos
  has_many :pacients
  #has_many :prms
  has_many :prm_causes
  has_many :diseases
  has_many :pharmacotherapies
  has_many :sfcs
  has_many :care_plans
    
  #belongs_to :pacient
  #belongs_to :prm
  #belongs_to :prm_cause
  #belongs_to :disease
  #belongs_to :pharmacotherapy
  #belongs_to :sfc
  #belongs_to :care_plan
  #Relacionamentos
  has_many :pacients
  has_many :prms
  has_many :prm_causes
  has_many :diseases
  has_many :pharmacotherapies
  has_many :sfcs
  has_many :care_plans
  has_many :attendances
  
    
  belongs_to :pacient
  belongs_to :prm
  belongs_to :prm_cause
  belongs_to :disease
  belongs_to :pharmacotherapy
  belongs_to :sfc
  belongs_to :care_plan
  belongs_to :attendance
  
  
  
    
end

app/controllers/pr_ms_controller.rb
class PrMsController < ApplicationController
  before_action :set_prm, only: [:show, :edit, :update, :destroy]

  # GET /prms
  # GET /prms.json
  def index
    @prms = Prm.all
  end

  # GET /prms/1
  # GET /prms/1.json
  def show
  end

  # GET /prms/new
  def new
    @prm = Prm.new
  end

  # GET /prms/1/edit
  def edit
  end

  # POST /prms
  # POST /prms.json
  def create
    @prm = Prm.new(prm_params)

    respond_to do |format|
      if @prm.save
        format.html { redirect_to @prm, notice: 'Prm was successfully created.' }
        format.json { render :show, status: :created, location: @prm }
      else
        format.html { render :new }
        format.json { render json: @prm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prms/1
  # PATCH/PUT /prms/1.json
  def update
    respond_to do |format|
      if @prm.update(prm_params)
        format.html { redirect_to @prm, notice: 'Prm was successfully updated.' }
        format.json { render :show, status: :ok, location: @prm }
      else
        format.html { render :edit }
        format.json { render json: @prm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prms/1
  # DELETE /prms/1.json
  def destroy
    @prm.destroy
    respond_to do |format|
      format.html { redirect_to prms_url, notice: 'Prm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prm
      @prm = Prm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prm_params
      params.require(:prm).permit(:description)
    end
end

app/controllers/prms_controller.rb
class PrmsController < ApplicationController
  before_action :authorize
  
  before_action :set_prm, only: [:show, :edit, :update, :destroy]

  # GET /prms
  # GET /prms.json
  def index
    if params[:pesquisa]
      @prms = Prm.pesquisa(params[:pesquisa])
    else
      @prms = Prm.all
    end
  end

  # GET /prms/1
  # GET /prms/1.json
  def show
  end

  # GET /prms/new
  def new
    @prm = Prm.new
  end

  # GET /prms/1/edit
  def edit
  end

  # POST /prms
  # POST /prms.json
  def create
    @prm = Prm.new(prm_params)

    respond_to do |format|
      if @prm.save
        format.html { redirect_to @prm, notice: 'PRM criado com sucesso.' }
        format.json { render :show, status: :created, location: @prm }
      else
        format.html { render :new }
        format.json { render json: @prm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prms/1
  # PATCH/PUT /prms/1.json
  def update
    respond_to do |format|
      if @prm.update(prm_params)
        format.html { redirect_to @prm, notice: 'PRM alterado com sucesso.' }
        format.json { render :show, status: :ok, location: @prm }
      else
        format.html { render :edit }
        format.json { render json: @prm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prms/1
  # DELETE /prms/1.json
  def destroy
    @prm.destroy
    respond_to do |format|
      format.html { redirect_to prms_url, notice: 'PRM deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prm
      @prm = Prm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prm_params
      params.require(:prm).permit(:description, :prm_causes, :pharmacotherapy_id, :prm_id, :sfc_id, :prmCause_id, :pacient_id)
    end
    
end

app/helpers/prms_helper.rb
module PrmsHelper
end

app/views/prms/_form.html.erb
<%= form_for(@prm) do |f| %>
  <% if @prm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prm.errors.count, "error") %> Não foi possivel salvar esse registro:</h2>

      <ul>
      <% @prm.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
<div class="container">
  <div class="row">
    <div class="col-md-12 col-sm-6 col-xs-12">
      <div class="panel panel-default">
        <div class="panel-body">
          <form class="form-horizontal row-border">
            <div class="form-group">
              <label class="col-md-2 control-label">Descrição:</label>
                  <%= f.text_field :description %>
                </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= f.submit 'Salvar', :class => 'btn btn-success' %>
  </div>
</div>
<% end %>

app/views/prms/edit.html.erb
<h1>Editando PRM</h1>

<%= render 'form' %>

<%= link_to 'Visualizar', @prm, :class => 'btn btn-primary' %> | <%= link_to 'Voltar', prms_path, :class => 'btn btn-primary' %>

app/views/prms/edit.js.erb
$('#user_form').html('<%= j render partial: "form" %>');
// $(".chosen-select").chosen();
chosen_init(); 

app/views/prms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de PRM(s)</h1>


<%= form_tag(prms_path, :method => :get) do %>
  <%= text_field_tag 'pesquisa', nil, placeholder: 'Buscar por PRM' %>
  <%= submit_tag "Pesquisar" , :class => 'btn btn-primary'%>
<% end %>

<table>
  <thead>
   
  </thead>

<%= link_to 'Novo PRM', new_prm_path, :class => 'btn btn-primary' %>


<%= form_tag(prms_path, :method => :get) do %>
 
<% end %>

<div class="container-fluid">
  <div class="row">
      <div class="col-sm-12">
       <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th>Descrição:</th>
              <th colspan="3">Ações</th>
            </tr>
          </thead>
        
          <tbody>
            <% @prms.each do |prm| %>
              <tr>
                <td><%= prm.description %></td>
                <td>
                    <div class="btn-group">    
                      <%= link_to '<i class="fa fa-folder"></i>'.html_safe, prm, :class => 'btn btn-info', "data-original-title" => "Visualizar", "data-placement" => "top", "data-toggle" => "tooltip" %>
                      <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_prm_path(prm), :class => 'btn btn-warning', "data-original-title" => "Editar", "data-placement" => "top", "data-toggle" => "tooltip" %>
                      <%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, prm, :class => 'btn btn-danger', method: :delete, data: { confirm: 'Confirma a exclusão?' }, "data-original-title" => "Delete", "data-placement" => "top", "data-toggle" => "tooltip" %>
                    </div>  
                </td> 
             </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/prms/new.html.erb
<%= link_to 'Voltar', prms_path, :class => 'btn btn-primary' %>

<h1>Novo PRM</h1>

<%= render 'form' %>

app/views/prms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descrição:</strong>
  <%= @prm.description %>
</p>

<%= link_to 'Editar', edit_prm_path(@prm), :class => 'btn btn-primary' %> | <%= link_to 'Voltar', prms_path, :class => 'btn btn-primary' %>